### ISSUE TITLE
Bug: Cant go back to Main Screen sometimes

### ISSUE THREAD

**Issue by vanitasvitae** [redfish64/TinyTravelTracker#3] opened 2015-10-10 05:12 UTC
Hi
Sometimes when I open the app from the notification I end up in the settingsActivity. From there I cant go to the main screen, neither the back soft key works, nor the menu entry "back to main screen". Both just close the app.

A workaround is to open the app from the launcher.

**Comment by vanitasvitae** [comment] 2015-10-10 12:51
Also I have the feeling, the app asks for the password way too often. Maybe you could add an optional timeout?

**Comment by C0R10L4NU2** [comment] 2015-10-11 22:26
I can confirm the "Cant go back to Main Screen" part

**Comment by redfish64** [comment] 2015-10-15 03:58
I added a password timeout. However, Tiny Travel Tracker won't write the password to disk (by design), so if the app is killed by the Android OS while in the background, which happens if Android runs out of memory, then you still will have to add your password.

I also updated the code to go to the main screen.

The fix will be in v1.0.13.

**Comment by redfish64** [comment] 2015-10-16 23:03
You can follow the merge request here:

https://gitlab.com/fdroid/fdroiddata/merge_requests/1017

Unfortunately, it seems there are some problems getting it pushed through.

**Comment by dreaming-augustin** [comment] 2015-11-07 02:27
The bug still exists with v1.0.14.
Here is how to reproduce:

Start the app (open it from the normal application launcher).
Once in the main screen, notice the three hardware buttons:
- the menu button is irrelevant here.
- the home button 'minimizes' the application without closing it.
- the return button somehow quits the application.

From the main window (map view), when GPS data gathering is enabled:
-> press home (minimizes the application which is no longer in view) > open notification drawer > press on the app status > app settings page > press 'return' gets you back to the main window, which is what is expected.
But:
-> press return (somehow quits the application window) > open notification drawer > press on the app status > app settings page > press 'return' does NOT get you back to the main window but to the smartphone home screen, which is the bug that the OP reported.

A straight fix shouldn't be too complicated.

However, should one day this app be blessed with a group of active developers, I don't think that the settings page is the right place for this toggle. The binary logic ON/OFF with a single percentage setting for the "Time the GPS is on" is too simplistic. We should be able to set the application in one of different modes:
- (completely) OFF 
- ON, Throttled, equivalent to the current ON behaviour.
- Intensive, for a more detailed data gathering mode.
- Continuous, like in the Google map app, where we can see in (almost) real time our progress on a map.
But these last comments may be better suited for another ticket, for a long term feature request...

**Closed** 2017-02-25 13:04 UTC
