### ISSUE TITLE
tiny travel tracker closes after start

### ISSUE THREAD

**Issue by paulle** [redfish64/TinyTravelTracker#2] opened 2015-10-06 16:54 UTC
I installed tiny travel tracker from f-droid. If try to start it, I get the message: tiny travel tracker was terminated. Rebooted the phone, installed tiny travel tracker from new, but the issue remains.
I'm using cm12.1 on a xperia z1c.

**Comment by vanitasvitae** [comment] 2015-10-06 19:20
I can confirm this. Im running CopperheadOS (hardened Android based on CM 12.1) on a Nexus 5.

**Comment by C0R10L4NU2** [comment] 2015-10-06 21:35
First, thank you for putting your app on fdroid.

I can confirm this issue on CM12.1/nexus6

**Comment by redfish64** [comment] 2015-10-07 01:18
Obfuscation was causing ACRA to throw an exception on launch on the release build. Fixed by disabling obfuscation.

**Comment by krt16s** [comment] 2015-10-07 19:40
Disabling the build, apk will be removed tonight. Did you already push 1.0.12? Doesn't seem to be in this repo?

**Comment by paulle** [comment] 2015-10-07 19:44
No in fdroid repo is till now v1.0.11.
If there is an update I would install it.

Am 7. Oktober 2015 21:40:26 MESZ, schrieb Boris Kraut <notifications@github.com>:
>Disabling the build, apk will be removed tonight. Did you already push
>1.0.12? Doesn't seem to be in this repo?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/redfish64/TinyTravelTracker/issues/2#issuecomment-146306076

-- 
K-9 Mail

**Comment by krt16s** [comment] 2015-10-07 20:53
I work on F-Droid, my comment was meant for @redfish64 since I cannot find the updated source code in this repo here. ^^

**Comment by paulle** [comment] 2015-10-07 20:55
OK no problem.

Am 7. Oktober 2015 22:53:03 MESZ, schrieb Boris Kraut <notifications@github.com>:
>I work on F-Droid, my comment was meant for @redfish64 since I cannot
>find the updated source code in this repo here. ^^
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/redfish64/TinyTravelTracker/issues/2#issuecomment-146324610

-- 
K-9 Mail

**Comment by redfish64** [comment] 2015-10-07 22:46
@krt16s You're right. I forgot to push it. It should be there now

**Comment by vanitasvitae** [comment] 2015-10-08 16:06
@krt16s The app disappeared from FDroid. Will it be added again? 

And is the current version working?

**Comment by krt16s** [comment] 2015-10-08 20:54
As I said, I disabled the build (which results in the apk being removed). I also added a new build with the new version, which should fix the issue. It's in the queue and will get build in tonight’s build run.

**Comment by paulle** [comment] 2015-10-09 19:12
Tony travel tracker is now in fdroid again (v1.0.12).
Installed perfect now, tracking I couldn't test for now (have to stay at home for 2 or 3 days).
Thank you.

**Comment by vanitasvitae** [comment] 2015-10-09 19:21
By checking out your app in FDroid I found a bug (in fdroid). The install button on the upper right has no text and is not clickable. I dont think, this is the right place to report the bug, but since I experienced this bug only on Tiny Travel Tracker so far ans since @krt16s is around and he works on fdroid...

**Comment by C0R10L4NU2** [comment] 2015-10-09 21:51
Thank you. The everything works. 

vanitasvitae, you might want to file a bug report for the fdroid app. This issue has nothing to do with tinytraveltracker. I have encountered it with various other apps, too. BTW, the workaround is to close  and restart fdroid.

**Comment by redfish64** [comment] 2015-10-10 00:39
Great, glad to hear it! Closing this

**Closed by redfish64** 2015-10-10 00:39 UTC

**Comment by ilf** [comment] 2015-11-03 23:29
I still get this with 1.0.14 from F-Droid. It worked well for a few days, then did this again. I haven't been able to open it in over a week without crashing immediately.

I can't find anything relevant in LogCat. How can I provide more useful debug information?

Thanks, and keep up the good work!

**Comment by redfish64** [comment] 2015-11-04 00:35
I don't have a server right now, so any crash reports aren't coming to me.

Can you pulldown the top bar, and select the frog to go to the settings
screen? If you can, go there, select backup/export and send me the file
(this is your gps log file, so of course only do this if you are
comfortable about me seeing where you've been).

In the logcat, if you grep for "rareventure", you should see an exception.
If you could send that, it would be helpful.

Thanks and sorry.

**Comment by ilf** [comment] 2015-11-25 22:49
I can reach the settings screen via the icon in the status bar and create a GPX export. Opening it, I can see it's still logging, but it has no information about a crash. So I'd rather not sent it, unless you can tell me why you need it :)

The logcat part shows this for the period of opening it until crash:

11-25 17:39:26.518 I/ActivityManager(2490): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.rareventure.gps2/.reviewer.map.OsmMapGpsTrailerReviewerMapActivity bnds=[544,619][704,819]} from pid 15051
11-25 17:39:29.213 I/ActivityManager(2490): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.rareventure.gps2/.reviewer.map.OsmMapGpsTrailerReviewerMapActivity bnds=[544,619][704,819]} from pid 15051
11-25 17:39:29.443 D/GpsTrailer(32028): Starting on intent Intent { cmp=com.rareventure.gps2/.GpsTrailerService }
11-25 17:39:29.448 D/GpsTrailer(32028): Starting on intent Intent { cmp=com.rareventure.gps2/.GpsTrailerService }
11-25 17:39:29.683 I/ActivityManager(2490): Displayed com.rareventure.gps2/.reviewer.map.OsmMapGpsTrailerReviewerMapActivity: +380ms
11-25 17:39:29.718 E/GpsTrailer(32028): Thread Thread[Thread-1755,5,main]: trace: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Object.java:364), com.rareventure.android.ProcessThread.run(ProcessThread.java:82)]
11-25 17:39:29.728 E/GpsTrailer(32028): Thread SelectedAreaSet [isRunning=true, isShutdown=false, rwtm=com.rareventure.util.ReadWriteThreadManager@41e28fc0, activity=com.rareventure.gps2.reviewer.map.OsmMapGpsTrailerReviewerMapActivity@41bee090, requestedAreas=[], requestedStartTimeSec=1445644307, requestedEndTimeSec=1445695050, resultPaths=null, resultTimeRangeTree=[], resultAreas=[], resultEndTime=1445695050, resultStartTime=1445644307, upToDate=true, distCalculated=true, timeZone=libcore.util.ZoneInfo[America/Bogota,mRawOffset=-18000000,mUseDst=false,mDstSavings=3600000]
11-25 17:39:29.728 E/GpsTrailer(32028): , p1=Point(0, 0), p2=Point(0, 0), lastTimeRange=null, lastIndex=0, observers=[android.widget.AbsListView$AdapterDataSetObserver@41ee5968], getTimeRangeTr=AreaTimeRange [fullRangeStartSec=0, fullRangeEndSec=0, dist=0.0, startTimeSec=0, endTimeSec=0], workerInterrupted=false, resultIncomplete=false, upToDateLock=java.lang.Object@41c727b0, t1TimeRange=AreaTimeRange [fullRangeStartSec=0, fullRangeEndSec=0, dist=0.0, startTimeSec=0, endTimeSec=0], t2TimeRange=AreaTimeRange [fullRangeStartSec=0, fullRangeEndSec=0, dist=0.0, startTimeSec=0, endTimeSec=0], resultId=1, isResultTimeTree=true]: trace: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Object.java:364), com.rareventure.gps2.reviewer.map.sas.SelectedAreaSet.run(SelectedAreaSet.java:295)]
11-25 17:39:29.733 E/GpsTrailer(32028): Thread class com.rareventure.android.SuperThread(Thread[Thread-1762,5,main]): trace: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Object.java:401), com.rareventure.android.SuperThread.run(SuperThread.java:194)]
11-25 17:39:29.733 E/GpsTrailer(32028): Thread class com.rareventure.android.SuperThread(Thread[Thread-1760,5,main]): trace: [com.rareventure.android.Util.byteArrayToInt(Util.java:249), com.rareventure.android.encryption.EncryptedRow.getInt(EncryptedRow.java:156), com.rareventure.gps2.database.cache.TimeTree.getSubNodeFk(TimeTree.java:492), com.rareventure.gps2.database.cache.TimeTree.getSubNode(TimeTree.java:483), com.rareventure.gps2.database.cache.TimeTree.getBottomLevelEncompassigTimeTree(TimeTree.java:881), com.rareventure.gps2.database.cachecreator.GpsTrailerCacheCreator.calcTrDist(GpsTrailerCacheCreator.java:241), com.rareventure.gps2.reviewer.map.GpsTrailerOverlayDrawer.doWork(GpsTrailerOverlayDrawer.java:253), com.rareventure.android.SuperThread.run(SuperThread.java:209)]
11-25 17:39:29.733 E/GpsTrailer(32028): Thread class com.rareventure.android.SuperThread(Thread[Thread-1761,5,main]): trace: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Object.java:401), com.rareventure.android.SuperThread.run(SuperThread.java:194)]
11-25 17:39:29.738 E/GpsTrailer(32028): Thread Thread[main,5,main]: trace: [android.graphics.Canvas.native_drawBitmap(Native Method), android.graphics.Canvas.drawBitmap(Canvas.java:1128), com.rareventure.gps2.reviewer.map.osm.MemoryCache.drawBitmap(MemoryCache.java:174), com.rareventure.gps2.reviewer.map.osm.MemoryCache.requestAndDrawRect(MemoryCache.java:107), com.rareventure.gps2.reviewer.map.OsmMapView.onDraw(OsmMapView.java:143), android.view.View.draw(View.java:13719), android.view.View.draw(View.java:13603), android.view.ViewGroup.drawChild(ViewGroup.java:2928), android.view.ViewGroup.dispatchDraw(ViewGroup.java:2797), android.view.View.draw(View.java:13601), android.view.ViewGroup.drawChild(ViewGroup.java:2928), android.view.ViewGroup.dispatchDraw(ViewGroup.java:2797), android.view.View.draw(View.java:13601), android.view.ViewGroup.drawChild(ViewGroup.java:2928), android.view.ViewGroup.dispatchDraw(ViewGroup.java:2797), android.view.View.draw(View.java:13601), android.view.ViewGroup.drawChild(ViewGroup.java:2928), android.view.ViewGroup.dispatchDraw(ViewGroup.java:2797), android.view.View.draw(View.java:13722), android.widget.FrameLayout.draw(FrameLayout.java:467), com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2473), android.view.ViewRootImpl.drawSoftware(ViewRootImpl.java:2281), android.view.ViewRootImpl.draw(ViewRootImpl.java:2177), android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2045), android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1854), android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:989), android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4351), android.view.Choreographer$CallbackRecord.run(Choreographer.java:749), android.view.Choreographer.doCallbacks(Choreographer.java:562), android.view.Choreographer.doFrame(Choreographer.java:532), android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735), android.os.Handler.handleCallback(Handler.java:725), android.os.Handler.dispatchMessage(Handler.java:92), android.os.Looper.loop(Looper.java:137), android.app.ActivityThread.main(ActivityThread.java:5227), java.lang.reflect.Method.invokeNative(Native Method), java.lang.reflect.Method.invoke(Method.java:511), com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795), com.android.internal.os.ZygoteInit.main(ZygoteInit.java:562), dalvik.system.NativeStart.main(Native Method)]
11-25 17:39:29.738 E/GpsTrailer(32028): Thread Thread[Thread-1754,5,main]: trace: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Object.java:401), com.rareventure.gps2.GpsTrailerGpsStrategy$GpsBatteryManager$1.run(GpsTrailerGpsStrategy.java:366)]
11-25 17:39:29.738 E/GpsTrailer(32028): Thread Thread[Thread-1757,5,main]: trace: [dalvik.system.VMStack.getThreadStackTrace(Native Method), java.lang.Thread.getStackTrace(Thread.java:591), java.lang.Thread.getAllStackTraces(Thread.java:528), com.rareventure.android.Util.printAllStackTraces(Util.java:1065), com.rareventure.gps2.database.cachecreator.GpsTrailerCacheCreator.run(GpsTrailerCacheCreator.java:413)]
11-25 17:39:29.738 E/ACRA    (32028): ACRA is disabled for com.rareventure.gps2 - forwarding uncaught Exception on to default ExceptionHandler
11-25 17:39:29.738 E/AndroidRuntime(32028): 	at com.rareventure.gps2.reviewer.map.MediaLocTimeMap.updateFromGallery(MediaLocTimeMap.java:440)
11-25 17:39:29.738 E/AndroidRuntime(32028): 	at com.rareventure.gps2.database.cachecreator.GpsTrailerCacheCreator.run(GpsTrailerCacheCreator.java:371)
11-25 17:39:29.738 W/ActivityManager(2490):   Force finishing activity com.rareventure.gps2/.reviewer.map.OsmMapGpsTrailerReviewerMapActivity
11-25 17:39:30.378 D/GpsTrailer(32028): Thread class com.rareventure.android.SuperThread(Thread[Thread-1760,5,main]) exited
11-25 17:39:30.378 D/GpsTrailer(32028): Thread class com.rareventure.android.SuperThread(Thread[Thread-1761,5,main]) exited
11-25 17:39:30.378 D/GpsTrailer(32028): Thread class com.rareventure.android.SuperThread(Thread[Thread-1762,5,main]) exited
11-25 17:39:31.253 I/ActivityManager(2490): Process com.rareventure.gps2 (pid 32028) has died.
11-25 17:39:31.253 W/ActivityManager(2490): Service crashed 2 times, stopping: ServiceRecord{42684b98 u0 com.rareventure.gps2/.GpsTrailerService}
11-25 17:39:59.963 I/ActivityManager(2490): Start proc com.rareventure.gps2 for broadcast com.rareventure.gps2/.bootup.GpsTrailerReceiver: pid=773 uid=10103 gids={50103, 3003, 1015, 1028}

**Comment by redfish64** [comment] 2015-11-26 00:33
Unfortunately, the log is showing the status of all threads after the
exception occurred, so I do not know the exact nature of the crash. I can
fix this problem, so the log shows the exact exception, which will bring us
one step forward, but it will mean a version bump for everyone, and I doubt
very much it will give me enough information to solve your issue.

The following will be a little hard to understand, but I'll try to explain
it the best I can.

The nature of your problem has to do with the code trying to place the
points in a lookup table for speedy access when displaying them to the map
(it groups several points near the same location into a single blob so when
you zoom out, it only has to lookup a few points rather than the whole
database). With a few thousand points, of course, this is not necessary,
but Tiny Travel Tracker is designed to handle even millions of points.

Basically the code runs in two parts. The first part is writing out the
points and happens in the background automatically (the server process).
This server process does not have the private key to your data (which is
there whether you set a password or not), and instead uses a public key to
encrypt points and then insert them in the database. With the public key,
it can only write points, it cannot read them. The private key, then, is
encrypted with a hash of your password, and so is unavailable until the
program starts and the password is asked for.

By doing all the above, I make it possible to log gps points, without
storing your password to disk. Instead the password is only ever stored in
memory after when you open the app and type it in.

In order to generate the lookup table, the code needs to be able to read
and write to the points, and it needs the private key to do this. So,
whenever you start the main app and enter the password, the code now has
the private key and immediately begins updating the lookup table with any
fresh points generated by the background app.

I can tell by the stack trace you gave me that the error is happening in
this code (specifically in GpsTrailerCacheCreator.java) during this lookup
table generator code. The problem is I don't know exactly where, and more
importantly, why.

Since I've been running the app for 5 years or so myself, with over half a
million points, travelling to many places in the world while doing so, and
other people seem to be not having this issue as far as I can tell (yours
is the first I've heard of it) I have to believe the issue must be
something to do with your location. Maybe you're near the equator, live in
Antarctica, near the North Pole, near the international date line, I don't
know... but I think there is something special about where you live :).

Anyway, I ran into a lot of bugs with the GpsTrailerCacheCreator when I
first built it, and they were mostly very complex and hard to debug That's
why I need your input data, so I can recreate the problem, because I'm at a
loss as to what to do without it.

If you like, you can trim down the exported file, and/or modify the
location of the points. As long as when you run Restore with them in the
app, and it recreates the issue, then I should be able to use it to find
and fix the problem.

Sorry about this, I don't know what else I can do to solve this for you.

**Comment by dreaming-augustin** [comment] 2015-11-26 06:56
The problem might be something very simple.

I've been using TTT for a few months without any major problem (no crash!). But two days ago, I experienced the very same symptoms as described above: the app would exit/crash straight away, as soon as I try to open it. I tried to reboot the phone, etc, as someone tried above, but to no avail. TTT was no longer working.
Then I noticed that somehow I had GPS turned off. I turned it on and TTT works again, as it did before.

So, to all the people who have been commenting on this thread: make sure GPS is turned ON, and try again.

In any case this is a bug. 
1) At the very least, the app should be accessible even with the GPS turned off, (e.g. to browse the maps and view past trips).
2) It would be a very good idea to warn the user that GPS if off (add a non-obtrusive warning somewhere on the main screen). 
3) Ideally, the app would offer a simple, in-app way to turn GPS on.

**Comment by dreaming-augustin** [comment] 2015-11-26 06:59
I just noticed that is issue is 'closed/fixed'.
So I opened a new issue with the bug I described in my previous comment: 
https://github.com/redfish64/TinyTravelTracker/issues/15

**Comment by ilf** [comment] 2015-11-29 14:42
redfish: I never enabled a password and the setting "enable password" is disabled.

I am indeed near the Equator and have recently crossed it, but the problem started quite a few degrees before.

I can send you my log. To which mail address?

The additional code for better logging and debugging sounds really useful, but it's up to you to decide if it justifies a version bump. I like "release early, release often". :)

dreaming-augustin: My GPS is enabled and my log is working. So your problem is different from mine.

**Comment by redfish64** [comment] 2015-12-01 01:47
On Sun, Nov 29, 2015 at 10:42 PM, ilf <notifications@github.com> wrote:

> redfish: I never enabled a password and the setting "enable password" is
> disabled.
>
Regardless, the system still encrypts the points. This was partly for ease
of programming (if everything works the same way it's easier to code/test)
and also so that when the app is uninstalled, there is no way to retrieve
the points from the sdcard, even if the deleted files are recovered.

> I am indeed near the Equator and have recently crossed it, but the problem
> started quite a few degrees before.
>
> I can send you my log. To which mail address?
>
engler@gmail.com
